name: ncov task
on:
  workflow_dispatch:
  schedule:
    #时间格式 minute hour day month week 设置的时间是UTC 不是北京时间
    - cron: "00 23 * * *"

jobs:
  start:
    # 运行环境为最新版的Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  

      #安装node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2  
        with:
          node-version: '14'

      # 安装依赖并且执行脚本
      - name: npm install
        run: npm install
      
      - name: Start task
        run: node ncov.js

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "update ncovInfo md file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}